import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getSession, SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <Suspense fallback={<div>Loading...</div>}>
        <html lang="en">
          <body className={inter.className}>
            <Toaster />
            <div className="h-full flex items-center justify-center bg-slate-300">
              {children}
            </div>
          </body>
        </html>
      </Suspense>
    </SessionProvider>
  );
}
